NWU-Website/NWU-Website/Controllers/VagtCentralController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NWU_Website.Models;
using System.Threading;

namespace NWU_Website.Controllers
{
    public class VagtCentralController : Controller
    {
        // GET: VagtCentral
        public ActionResult Index()

        {

            // Obejct who holds data we send to View and can use with @Model.? - Claus

            //VagtCentralChartsValues vcObj = new VagtCentralChartsValues();

            ChartData chartData = new ChartData();



            // Create a context who controlls access to the DB.

            // The using block close and run dispose after - Claus 

            // TalTabelContext er forbindelsen på Claus's computer til lokal DB



            using (var context = new nwuDB1Entities2())

            {

                //Area 1 Minigolf

                //get max and name

                var area1 = context.omraade.Where(s => s.omraadeID == 1);

                chartData.MaxNumber.Add(area1.First().maxAntal);

                chartData.AreaNames.Add(area1.First().omraadreNavn);



                //get current number in area

                var area1Current = context.checkIND.Where(s => s.checkindID == 3);

                chartData.CurrentNumber.Add(area1Current.First().antalPersoner);





                //Area 2 Abeland

                //get max and name

                var area2 = context.omraade.Where(s => s.omraadeID == 2);

                chartData.MaxNumber.Add(area2.First().maxAntal);

                chartData.AreaNames.Add(area2.First().omraadreNavn);



                //get current number in area

                var area2Current = context.checkIND.Where(s => s.checkindID == 4);

                chartData.CurrentNumber.Add(area2Current.First().antalPersoner);





                //Area 3 Fitness

                //get max and name

                var area3 = context.omraade.Where(s => s.omraadeID == 3);

                chartData.MaxNumber.Add(area3.First().maxAntal);

                chartData.AreaNames.Add(area3.First().omraadreNavn);



                //get current number in area

                var area3Current = context.checkIND.Where(s => s.checkindID == 6);

                chartData.CurrentNumber.Add(area3Current.First().antalPersoner);



                //Area 4 Wellness

                //get max and name

                var area4 = context.omraade.Where(s => s.omraadeID == 4);

                chartData.MaxNumber.Add(area4.First().maxAntal);

                chartData.AreaNames.Add(area4.First().omraadreNavn);



                //get current number in area

                var area4Current = context.checkIND.Where(s => s.checkindID == 7);

                chartData.CurrentNumber.Add(area4Current.First().antalPersoner);





                //Area 5 Vandrutsjebaner

                //get max and name

                var area5 = context.omraade.Where(s => s.omraadeID == 5);

                chartData.MaxNumber.Add(area5.First().maxAntal);

                chartData.AreaNames.Add(area5.First().omraadreNavn);



                //get current number in area

                var area5Current = context.checkIND.Where(s => s.checkindID == 8);

                chartData.CurrentNumber.Add(area5Current.First().antalPersoner);



                //Area 6 River rafting

                //get max and name

                var area6 = context.omraade.Where(s => s.omraadeID == 6);

                chartData.MaxNumber.Add(area6.First().maxAntal);

                chartData.AreaNames.Add(area6.First().omraadreNavn);



                //get current number in area

                var area6Current = context.checkIND.Where(s => s.checkindID == 9);

                chartData.CurrentNumber.Add(area6Current.First().antalPersoner);



                //Area 7 Lazy river

                //get max and name

                var area7 = context.omraade.Where(s => s.omraadeID == 7);

                chartData.MaxNumber.Add(area7.First().maxAntal);

                chartData.AreaNames.Add(area7.First().omraadreNavn);



                //get current number in area

                var area7Current = context.checkIND.Where(s => s.checkindID == 10);

                chartData.CurrentNumber.Add(area7Current.First().antalPersoner);



                //Area 8 Splashzone

                //get max and name

                var area8 = context.omraade.Where(s => s.omraadeID == 8);

                chartData.MaxNumber.Add(area8.First().maxAntal);

                chartData.AreaNames.Add(area8.First().omraadreNavn);



                //get current number in area

                var area8Current = context.checkIND.Where(s => s.checkindID == 11);

                chartData.CurrentNumber.Add(area8Current.First().antalPersoner);



                //Area 9 soppebassin

                //get max and name

                var area9 = context.omraade.Where(s => s.omraadeID == 9);

                chartData.MaxNumber.Add(area9.First().maxAntal);

                chartData.AreaNames.Add(area9.First().omraadreNavn);



                //get current number in area

                var area9Current = context.checkIND.Where(s => s.checkindID == 12);

                chartData.CurrentNumber.Add(area9Current.First().antalPersoner);



                //Area 10 bølgebassin

                //get max and name

                var area10 = context.omraade.Where(s => s.omraadeID == 10);

                chartData.MaxNumber.Add(area10.First().maxAntal);

                chartData.AreaNames.Add(area10.First().omraadreNavn);



                //get current number in area

                var area10Current = context.checkIND.Where(s => s.checkindID == 13);

                chartData.CurrentNumber.Add(area10Current.First().antalPersoner);



                //Area 11 Vandfald

                //get max and name

                var area11 = context.omraade.Where(s => s.omraadeID == 11);

                chartData.MaxNumber.Add(area11.First().maxAntal);

                chartData.AreaNames.Add(area11.First().omraadreNavn);



                //get current number in area

                var area11Current = context.checkIND.Where(s => s.checkindID == 14);

                chartData.CurrentNumber.Add(area11Current.First().antalPersoner);

            }

            // Pause the method for 5 seconds - Claus

            //Thread.Sleep(5000);



            // return the object to the View - Claus

            return View(chartData);

        }





        public ActionResult RunningDemo()

        {



            return View();

        }



        public ActionResult ShowHistoryData(int? area, string dato)
        {

            HistoryData ttc = new HistoryData();
            nwuDB1Entities3 db = new nwuDB1Entities3();

            // if area is assigned a value
            if (area.HasValue)
            {
                // put all data from the table checkIND where kortlaeserID is the same as area into test
                var test = db.checkINDs.Where(o => o.kortlaeserID == area);

                // sort after date and time
                test = test.OrderBy(o => o.ckeckIND);

                // we transform a var result to a list<checkIND> result
                List<checkIND> testRedultater = test.ToList<checkIND>();


                ttc.Tal1 = (int)testRedultater.ElementAt(0).antalPersoner; //first result
                ttc.Tal2 = (int)testRedultater.ElementAt(1).antalPersoner;
                ttc.Tal3 = (int)testRedultater.ElementAt(2).antalPersoner;
                ttc.Tal4 = (int)testRedultater.ElementAt(3).antalPersoner;
                ttc.Tal5 = (int)testRedultater.ElementAt(4).antalPersoner;
                ttc.Tal6 = (int)testRedultater.ElementAt(5).antalPersoner;
                ttc.Tal7 = (int)testRedultater.ElementAt(6).antalPersoner;
                ttc.Tal8 = (int)testRedultater.ElementAt(7).antalPersoner;
                ttc.Tal9 = (int)testRedultater.ElementAt(8).antalPersoner;
                ttc.Tal10 = (int)testRedultater.ElementAt(9).antalPersoner;
                ttc.Tal11 = (int)testRedultater.ElementAt(10).antalPersoner;
            }

            return View(ttc);
        }
    }
}

NWU-Website/NWU-Website/Views/VagtCentral/Index.cshtml
@*Values from About method is put into @Model - Claus*@
@*@model NWU_Website.Models.VagtCentralChartsValues*@
@model NWU_Website.Models.ChartData
@using NWU_Website.Controllers;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <style>
        .ppp {
            /*float: left;*/
        }
    </style>

    @*Get and load Google Charts loader - Claus*@
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        //Get newest version of Google Charts and load Chart package
        //language is set to dk - Claus
        google.charts.load('current', { 'packages': ['gauge'], 'language': 'dk' });


        //Set methodes to run when Google Charts loader is ready - Claus
        google.charts.setOnLoadCallback(draw1Chart);
        google.charts.setOnLoadCallback(draw2Chart);
        google.charts.setOnLoadCallback(draw3Chart);
        google.charts.setOnLoadCallback(draw4Chart);
        google.charts.setOnLoadCallback(draw5Chart);
        google.charts.setOnLoadCallback(draw6Chart);
        google.charts.setOnLoadCallback(draw7Chart);
        google.charts.setOnLoadCallback(draw8Chart);
        google.charts.setOnLoadCallback(updatePage);

        // Method refresh the page - Claus
        function updatePage()
        {
            //location.reload(false);
        }

        //Method draw a Gauge chart with text, color and numbers - Claus
        function draw1Chart() {
            var name = "@Model.AreaNames.ElementAt(0)"; //save model val in javascript

            //value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                [name, 1] //value must be > 0, or it dies...
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: @Model.MaxNumber.ElementAt(0),
                redFrom: 180, redTo: 200,
                yellowFrom: 150, yellowTo: 180,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div1 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div1'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, @Model.CurrentNumber.ElementAt(0));

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

          //Method draw a Gauge chart with text, color and numbers - Claus
        function draw2Chart() {
            var name = "@Model.AreaNames.ElementAt(1)";
            // Model.Tal2 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                [name, 2]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: @Model.MaxNumber.ElementAt(1),
                redFrom: 270, redTo: 300,
                yellowFrom: 225, yellowTo: 270,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div2 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div2'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, @Model.CurrentNumber.ElementAt(1));

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

         //Method draw a Gauge chart with text, color and numbers - Claus
        function draw3Chart() {

            // Model.Tal3 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                ['Minigolf', 0]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: 160,
                redFrom: 144, redTo: 160,
                yellowFrom: 120, yellowTo: 144,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div3 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div3'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, 0);

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

         //Method draw a Gauge chart with text, color and numbers - Claus
        function draw4Chart() {

            // Model.Tal1 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                ['Abeland', 0]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: 300,
                redFrom: 270, redTo: 300,
                yellowFrom: 225, yellowTo: 270,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div4 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div6'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, 0);

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

         //Method draw a Gauge chart with text, color and numbers - Claus
        function draw5Chart() {

            // Model.Tal1 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                ['Vandfald', 0]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: 100,
                redFrom: 90, redTo: 100,
                yellowFrom: 75, yellowTo: 90,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div5 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div5'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, 0);

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

         //Method draw a Gauge chart with text, color and numbers - Claus
        function draw6Chart() {

            // Model.Tal6 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                ['Soppebassin', 0]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: 160,
                redFrom: 144, redTo: 160,
                yellowFrom: 120, yellowTo: 144,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div6 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div4'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, 0);

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

         //Method draw a Gauge chart with text, color and numbers - Claus
        function draw7Chart() {

            // Model.Tal1 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                ['Fitness', 0]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: 200,
                redFrom: 180, redTo: 200,
                yellowFrom: 150, yellowTo: 180,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div7 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div7'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, 0);

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }

         //Method draw a Gauge chart with text, color and numbers - Claus
        function draw8Chart() {

            // Model.Tal1 is the value from database - Claus
            var data = google.visualization.arrayToDataTable([
                ['Label', 'Value'],
                ['Cafe', 0]
            ]);

            //Here we set Max Numbers and other visual options - Claus
            var options = {
                max: 100,
                redFrom: 90, redTo: 100,
                yellowFrom: 75, yellowTo: 90,
                minorTicks: 1
            };

            // Create a chart of type Gauge and place it in the <body> where id = chart_div8 - Claus
            var chart = new google.visualization.Gauge(document.getElementById('chart_div8'));

            //Set Gauge value from database - Claus
            data.setValue(0, 1, 0);

            //Draw chart with data and options - Claus
            chart.draw(data, options);
        }


    </script>
</head>

<body style="background-color:midnightblue;">

    @*Ved at pakke alt ind i <div></div> og bruge col-lg-tal
        kan vi styre placering af de 8 Gauge-meter og alt tekst - Claus*@
    <div align="center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" align="center">
                    <h1 style="color:white;font-family:verdana;">Nordic Water Universe</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12" align="center">
                    <h2 style="color:white;font-family:verdana;">Vagtcentral</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-1"></div>
                <div class="col-lg-4" align="center">
                    <h4 style="color:white;font-family:verdana;">Livredder Områder</h4>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-1"></div>
                <div class="col-lg-4" align="center">
                    <h4 style="color:white;font-family:verdana;">Vagt Områder</h4>
                </div>
                <div class="col-lg-1"></div>
            </div>
            <div class="ppp">
                <div style="display:inline-block">
                    <div class="col-lg-1" style="background-color:midnightblue;"></div>

                    <div style="display:inline-block" class="col-lg-2" >
                        <div id="chart_div1" style="width: 290px; height: 180px;"></div>
                    </div>
                    <div style="display:inline-block" class="col-lg-2" >
                        <div id="chart_div2" style="width: 290px; height: 180px;"></div>
                    </div>

                    <div class="col-lg-1" style="background-color:midnightblue;"></div>
                    <div class="col-lg-1" style="background-color:midnightblue;"></div>


                    <div class="col-lg-2" style="display:inline-block">
                        <div id="chart_div3" style="width: 290px; height: 180px;"></div>
                    </div>
                    <div class="col-lg-2" style="display:inline-block">
                        <div id="chart_div4" style="width: 290px; height: 180px;"></div>
                    </div>

                    <div class="col-lg-1" style="background-color:midnightblue;"></div>
                </div>

                <div class="row">
                    <div class="col-lg-1" style="background-color:midnightblue;"></div>

                    <div class="col-lg-2" style="display:inline-block">
                        <div id="chart_div5" style="width: 290px; height: 180px;"></div>
                    </div>
                    <div class="col-lg-2" style="display:inline-block">
                        <div id="chart_div6" style="width: 290px; height: 180px;"></div>
                    </div>

                    <div class="col-lg-1" style="background-color:midnightblue;"></div>
                    <div class="col-lg-1" style="background-color:midnightblue;"></div>


                    <div class="col-lg-2" style="display:inline-block">
                        <div id="chart_div7" style="width: 290px; height: 180px;"></div>
                    </div>
                    <div class="col-lg-2" style="display:inline-block">
                        <div id="chart_div8" style="width: 290px; height: 180px;"></div>
                    </div>

                    <div class="col-lg-1" style="background-color:midnightblue;"></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

NWU-Website/NWU-Website/Views/VagtCentral/ShowHistoryData.cshtml
@model NWU_Website.Models.HistoryData
@using NWU_Website.Controllers;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    @*Get and load Google Charts loader - Claus*@
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", { packages: ['corechart', 'bar'] });
        google.charts.setOnLoadCallback(drawStacked);
        function drawStacked() {
            var data = new google.visualization.DataTable();
            data.addColumn('timeofday', 'Tid på dagen');
            data.addColumn('number', 'Besøgende');

            data.addRows([
                [{ v: [7, 0, 0], f: '7:00' }, @Model.Tal1],
                [{ v: [8, 0, 0], f: '8:00' }, @Model.Tal2],
                [{ v: [9, 0, 0], f: '9:00' }, @Model.Tal3],
                [{ v: [10, 0, 0], f: '10:00' }, @Model.Tal4],
                [{ v: [11, 0, 0], f: '11:00' }, @Model.Tal5],
                [{ v: [12, 0, 0], f: '12:00' }, @Model.Tal6],
                [{ v: [13, 0, 0], f: '13:00' }, @Model.Tal7],
                [{ v: [14, 0, 0], f: '14:00' }, @Model.Tal8],
                [{ v: [15, 0, 0], f: '15:00' }, @Model.Tal9],
                [{ v: [16, 0, 0], f: '16:00' }, @Model.Tal10],
                [{ v: [17, 0, 0], f: '17:00' }, @Model.Tal11],
            ]);

            var options = {
                title: 'Antal besøgende på et bestemt tidpunkt af dagen',
                isStacked: true,
                hAxis: {
                    title: 'Tid på Dagen',
                    format: 'h:mm a',
                    viewWindow: {
                        min: [6, 30, 0],
                        max: [17, 30, 0]
                    }
                },
                vAxis: {
                    title: 'Besøgende'
                }
            };
            var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
            chart.draw(data, options);
        }
    </script>




</head>
<body>

    @using (Html.BeginForm("ShowHistoryData", "VagtCentral", FormMethod.Get))
    {

        <div class="row form-group">

            <div class="col-md-2">
                <form action="">
                    <input type="radio" name="area" value="1"> Minigolf<br>
                    <input type="radio" name="area" value="2"> Abeland<br>
                    <input type="radio" name="area" value="3"> Fitness<br>
                    <input type="radio" name="area" value="4"> Cafe<br>
                    <input type="radio" name="area" value="11"> Vandfald<br>
                    <input type="radio" name="area" value="10"> Bølgebassin<br>
                    <input type="radio" name="area" value="8"> Splashbassin<br>
                    <input type="radio" name="area" value="9"> Soppebassin<br>

                </form>
            </div>

            <div class="col-md-2">
                @Html.TextBox("dato", "{0:yyyy-MM-dd HH:mm:ss}", new { @class = "date-picker", @type = "date" })
            </div>


            <button type="submit" class="btn btn-default">Hent</button>
        </div>

    }

    <div id="columnchart_values" style="width: 1150px; height: 350px;"></div>
</body>
</html>